(ns skidskytte.namer)

(def nationalities [
                    "amerikansk"
                    "baltisk"
                    "brittisk"
                    "dansk"
                    "finsk"
                    "fransk"
                    "nordisk"
                    "norsk"
                    "rysk"
                    "tysk"
                    ])
(def prefixes [
               "armbrytnings"
               "backhoppnings"
               "badminton"
               "bandy"
               "baseboll"
               "basket"
               "biljard"
               "bordtennis"
               "boule"
               "bowling"
               "boxnings"
               "breakdance"
               "bridge"
               "brottnings"
               "brännboll"
               "bänkpress"
               "bågskytte"
               "curling"
               "cykel"
               "dart"
               "diskus"
               "dragkamps"
               "dubbel"
               "dyknings"
               "enduro"
               "fallskärmshopps"
               "forspaddlings"
               "fotbolls"
               "frisbee"
               "fäktnings"
               "golf"
               "gång"
               "handbolls"
               "hockey"
               "häcklöpnings"
               "häst"
               "höjdhopps"
               "inlines"
               "innebandy"
               "isjakts"
               "judo"
               "kanot"
               "karate"
               "kendo"
               "klättrings"
               "konstsims"
               "konståknings"
               "krocket"
               "lacrosse"
               "landhockey"
               "längdhopps"
               "löpnings"
               "maraton"
               "orienterings"
               "polo"
               "ponny"
               "rally"
               "rodd"
               "rodel"
               "rugby"
               "seglings"
               "segway"
               "simhopps"
               "simnings"
               "skateboard"
               "skid"
               "skoter"
               "skridsko"
               "skytte"
               "slalom"
               "slungbolls"
               "slägg"
               "snowboard"
               "speedway"
               "spjut"
               "sprint"
               "stavhopps"
               "studsmatte"
               "styrkelyfts"
               "störtlopps"
               "sumobrottning"
               "taekwando"
               "telemarks"
               "tennis"
               "tjurfäktnings"
               "trampolin"
               "trestegs"
               "tyngdlyftnings"
               "undervattens"
               "vatten"
               "vattenskids"
               "volleyboll"
               "windsurfings"
               ])

(def suffixes [
               "armbrytning"
               "backhoppning"
               "badminton"
               "bandy"
               "baseboll"
               "basket"
               "biljard"
               "bordtennis"
               "boule"
               "bowling"
               "boxning"
               "breakdance"
               "bridge"
               "brottning"
               "brännboll"
               "bänkpress"
               "bågskytte"
               "casting"
               "curling"
               "cykel"
               "dart"
               "diskus"
               "dragkamp"
               "dykning"
               "enduro"
               "fallskärmshopp"
               "forspaddling"
               "fotboll"
               "frisbee"
               "fäktning"
               "golf"
               "gång"
               "handboll"
               "hockey"
               "häcklöpning"
               "höjdhopp"
               "innebandy"
               "judo"
               "kanot"
               "karate"
               "kendo"
               "klättring"
               "konstsim"
               "konståkning"
               "krocket"
               "lacrosse"
               "landhockey"
               "lerduveskytte"
               "längdhopp"
               "löpning"
               "maraton"
               "orientering"
               "polo"
               "rally"
               "rodd"
               "rodel"
               "rodeo"
               "rugby"
               "segling"
               "simhopp"
               "simning"
               "skateboard"
               "skoter"
               "skidor"
               "skridsko"
               "skytte"
               "slalom"
               "slungboll"
               "slägga"
               "snooker"
               "snowboard"
               "speedway"
               "spjut"
               "stafett"
               "stavhopp"
               "styrkelyft"
               "störtlopp"
               "sumobrottning"
               "taekwando"
               "tennis"
               "tjurfäktning"
               "tresteg"
               "tyngdlyftning"
               "varpa"
               "vattenskidor"
               "volleyboll"
               "windsurfing"
               ])


(defn random-word [word-list]
  (first (shuffle word-list)))

(defn has-nationality? []
  (= (rand-int 20) 1))

(defn nationality []
  (if (has-nationality?)
    (str (random-word nationalities) " ")
    ""))

(defn random-first-word []
  (random-word prefixes))

(defn random-second-word []
  (random-word suffixes))

(defn same-word-twice [word]
  (not (nil? (re-find #"(.{4,}).*\1" word))))

(defn two-sports []
  (str (nationality) (random-first-word) (random-second-word)))

(defn new-sport []
  (let [word (two-sports)]
    (if (same-word-twice word)
      (new-sport)
      word)))
